IF
	Global("psTeosRetrieveArtifactQuest","GLOBAL",1)
THEN
	RESPONSE #100
		CreateCreature("psTrait",[1051.279],0) // Traitor
		SetGlobal("psTeosRetrieveArtifactQuest","GLOBAL",2)
		Continue()
END

IF
	Allegiance("psTrait",ENEMY)
	Global("psRedWizardTrapSpawnToggle","GLOBAL",0)
THEN
	RESPONSE #100
		CreateCreatureDoor("psRedW2",[1142.369],4) // Red Wizard
		SetGlobal("psRedWizardTrapSpawnToggle","GLOBAL",1)
		Continue()
END



