IF
	True()
THEN
	RESPONSE #100
		CutSceneID("psMel")
		Wait(1)
		CreateVisualEffectObject("SPGRWHRL",Myself)
		Wait(1)
		CreateVisualEffectObject("SPGFLSH1",Myself)
		SmallWait(1)
		FadeToColor([30.0],0)
		Wait(2)
		Explore()
		FadeFromColor([30.0],0)
		MoveViewObject(Player1,INSTANT)
		SetGlobal("psFinalQuestToKillMelCounter", "GLOBAL", 6)
		ActionOverride("psLordAo", StartDialogNoSet(Player1))
		EndCutSceneMode()
		DestroySelf()
END