IF
	GlobalLT("psFourthSplitCounter", "GLOBAL", 15)
	HPLT(Myself, 50)
	Global("psFourthSplit", "LOCALS", 0)
THEN
	RESPONSE #100
		SetGlobal("psFourthSplit", "LOCALS", 1)
		IncrementGlobal("psFourthSplitCounter", "GLOBAL", 1)
		ApplySpellRes("psBlur", Myself)
		Wait(1)
		CreateCreatureObject("psSplit4", Myself, 0, 0, 0)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Attack(LastSeenBy)
		Continue()
END